apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: website
    app.kubernetes.io/version: 'fe9e64c'
  name: website
  namespace: ilogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: website
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: website
        app.kubernetes.io/version: 'fe9e64c'
    spec:
      containers:
        - image: registry.digitalocean.com/munyaal-docr/ilogs/website:fe9e64c
          name: website
          ports:
            - containerPort: 8080
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: website
  name: website
  namespace: ilogs
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: website
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
  namespace: ilogs
spec:
  ingressClassName: nginx
  rules:
    - host: enlaces.munyaal.com.mx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80       
  tls:
    - hosts:
        - descubre.ilogs.com.mx
      secretName: ilogs-com-mx-tls